### ISSUE TITLE
Problem : option --bin_dirs read all file even entries starting with .

### ISSUE THREAD

**Issue by bpenaud** [genotoul-bioinfo/Binette#14]
Hello,

I'm contacting you because I've been trying to use binette with the --bin_dirs option as part of a snakemake script. However, my snakemake script automatically generates .snakemake_timestamp files in my output directories (bin directory with the fasta of my bins). So, when I execute binnette I get an error because the .snakemake_timestamp file is read and doesn't correspond to a fasta file: "RuntimeError: concoct_bins/.snakemake_timestamp is not plain or gzip compressed fasta formatted file"

Regards,
Benjamin

**Comment by JeanMainguy** [comment]
Hello, 

Thanks for pointing this out!

I see a couple of options here: either ignoring hidden files or let the user specify file extensions in the command line.

Both solutions should be quick and easy to roll out. I'll get on this ASAP.

Thanks again for reporting it!

Best

**Comment by JeanMainguy** [comment]
Hello,
Just released a new version that lets you specify the FASTA extensions you want to look for, so hidden files won't get picked up anymore.

You can grab it on Bioconda and PyPI. If you run into any issues with this fix, just reopen the issue and let me know.

Cheers,
