### ISSUE TITLE
Documentation on seeking help

### ISSUE THREAD

**Issue by lskatz** [genotoul-bioinfo/Binette#20]
For the JOSS review at <https://github.com/openjournals/joss-reviews/issues/6782>.

According to the guidelines, can you add in a statement on how to seek help or support for the software? Thank you! 

![image](https://github.com/genotoul-bioinfo/Binette/assets/14798/1cb09e49-ad1a-4d71-a3a9-7ee6d1539413)

**Comment by JeanMainguy** [comment]
Hi,

Thanks for the feedback!  
Support is provided through the GitHub issues page. I've added info to clarify that to both the README ([here](https://github.com/genotoul-bioinfo/Binette?tab=readme-ov-file#help-feature-requests-and-bug-reporting)) and the documentation ([here](https://binette.readthedocs.io/en/latest/contributing.html#help-or-reporting-a-bug)). 
    
Best,

**Comment by lskatz** [comment]
Perfect. There are a couple of questions left here <https://github.com/openjournals/joss-reviews/issues/6782#issuecomment-2187193217> and then a tutorial via #19 and then I think I can accept!
